export const clientes = [
    {
        id: "1283b12b391263c23",
        name: "Antonieta Vasconcellos",
        image: "",
        identity: "",
        document: ["985.283.845-12"],
        email: "antonieta@gmail.com",
        contact: "55+ (45) 99867-1234",
        projects: [
            {
                id: "1283b12b391263c23",
                name: "Hotel Antônio Rebouças",
            },
        ],
        address: "Avenida Paulista, 9818",
    },
    {
        id: "89273b8ja0ja0sd9j0a",
        name: "Paulo Antonio Guedes",
        image: "",
        document: "323.564.723-12",
        email: "antonieta@gmail.com",
        contact: "55+ (45) 99867-1234",
        projects: [],
        address: "Avenida Paulista, 9818",
    },
    {
        id: "9574q9dj90a8da088903",
        name: "Diego Carlos Mendez",
        image: "",
        document: "123.456.789-12",
        email: "antonieta@gmail.com",
        contact: "55+ (45) 99867-1234",
        projects: [
            {
                id: "1283b12b391263c23",
                name: "Hotel Antônio Rebouças",
            },
        ],
        address: "Avenida Paulista, 9818",
    },
];

export const projetos = [
    {
        id: "1283b12b391263c23",
        name: "Planejamento Arquitêtonico  Prédio Rebouças",
        image: [""],
        clientName: "Antonieta Vasconcellos",
        clientId: "323.564.723-12",
        address: "Hotel Antônio Rebouças",
        addresComplement:
            "Perto do antigo prédio Osvaldo Cruz, ao lado do hospital interino de Pediatria",
        cep: "080908-8090",
        finishDate: "12/05/2022",
        description:
            "Projeto arquitetonico do prédio Rebouças, que deverá conter 15 andares de 300 M², 2 piscinas de 50 M² e 3 lounges ao lado direito do prédio ",
        docs: [
            { label: "TESTE I", doc: null },
            { label: "TESTE II", doc: null },
            { label: "TESTE III", doc: null },
            { label: "TESTE IV", doc: null },
            { label: "TESTE V", doc: null },
            { label: "TESTE VI", doc: null },
            { label: "TESTE VII", doc: null },
            { label: "TESTE VIII", doc: null },
            { label: "TESTE IX", doc: null },
            { label: "TESTE X", doc: null },
            { label: "TESTE XI", doc: null },
            { label: "TESTE XII", doc: null },
            { label: "TESTE XIII", doc: null },
            { label: "TESTE XIV", doc: null },
            { label: "TESTE XV", doc: null },
            { label: "TESTE XVI", doc: null },
            { label: "TESTE XVII", doc: null },
            { label: "TESTE XVIII", doc: null },
            { label: "TESTE XIX", doc: null },
            { label: "TESTE XX", doc: null },
            { label: "TESTE XXI", doc: null },
            { label: "TESTE XXII", doc: null },
            { label: "TESTE XXIII", doc: null },
        ],
        mapsPinPoint: {
            lat: -15.7983419,
            long: -47.8777281,
        },
        subProjects: [
            {
                project: "1283b12b391263c23",
                name: "Planejamento de custeio de honorario do Hotel Antônio Rebouças",
                params: {
                    _id: "90jadw0h8wq3kojrd0-q93uejq0od",
                    pv: 46110.6,
                    vm: 92.22,
                    sc: 500,
                    bh: 3680.31,
                    fp: 7.37,
                    sr: 0,
                    fcmar: 0.34,
                },
                type: "Custeio",
            },
            {
                project: "1283b12b391263c23",
                name: "Planejamento de custeio de honorario do Hotel Antônio Rebouças",
                params: {
                    _id: "90jadw0h8wq3kojrd0-q93uejq0od",
                    pv: 46110.6,
                    vm: 92.22,
                    sc: 500,
                    bh: 3680.31,
                    fp: 7.37,
                    sr: 0,
                    fcmar: 0.34,
                },
                type: "Custeio",
            },
        ],
        clientes: [
            {
                id: "1283b12b391263c23",
                name: "Antonieta Vasconcellos",
                image: "",
                identity: "",
                document: ["985.283.845-12"],
                email: "antonieta@gmail.com",
                contact: "55+ (45) 99867-1234",
                projects: [
                    {
                        id: "1283b12b391263c23",
                        name: "Hotel Antônio Rebouças",
                    },
                ],
                address: "Avenida Paulista, 9818",
            },
        ],
    },

    {
        id: "89273b8ja0ja0sd9j0a",
        name: "Planejamento Arquitêtonico  Prédio Rebouças",
        images: [],
        clients: [],
        dateStart: [],
        dateFinish: [],
        addressComplement: [],
        address: [],
        cep: "",
        localizationMap: {
            lat: -15.7983419,
            long: -47.8777281,
        },
        description:
            "O projeto deverá conter 15 andares de 300 M², 2 piscinas de 50 M² e 3 lounges ao lado direito do prédio ",
        subprojects: [],
    },
];
